version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.10.4
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /backend/pb_data:/pb_data
      - /backend/pub_public:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5